#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("LottoryApp.Resource", IsApplication=true)]

namespace LottoryApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public const int adSize = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int adSizes = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int adUnitId = 2130771973;
			
			// aapt resource value: 0x7f010002
			public const int circleCrop = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int imageAspectRatio = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int imageAspectRatioAdjust = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f070001
			public const int theme_black_notitlebar_background = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int theme_devicedefault_background = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int theme_devicedefault_light_noactionbar_background = 2131165184;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08000b
			public const int CanAdView = 2131230731;
			
			// aapt resource value: 0x7f080017
			public const int CanLotto = 2131230743;
			
			// aapt resource value: 0x7f08000f
			public const int GenerateCustom = 2131230735;
			
			// aapt resource value: 0x7f08001d
			public const int GoodLuck = 2131230749;
			
			// aapt resource value: 0x7f08001a
			public const int Greeting = 2131230746;
			
			// aapt resource value: 0x7f080006
			public const int LottoMax = 2131230726;
			
			// aapt resource value: 0x7f080014
			public const int LowerBonusLimit = 2131230740;
			
			// aapt resource value: 0x7f080011
			public const int LowerLimit = 2131230737;
			
			// aapt resource value: 0x7f080020
			public const int MegaMillionsButton = 2131230752;
			
			// aapt resource value: 0x7f08001e
			public const int NumAdView = 2131230750;
			
			// aapt resource value: 0x7f08001b
			public const int Numbers = 2131230747;
			
			// aapt resource value: 0x7f080004
			public const int Ont649 = 2131230724;
			
			// aapt resource value: 0x7f080009
			public const int Pick2 = 2131230729;
			
			// aapt resource value: 0x7f080008
			public const int Pick3 = 2131230728;
			
			// aapt resource value: 0x7f080007
			public const int Pick4 = 2131230727;
			
			// aapt resource value: 0x7f08001f
			public const int PowerBallButton = 2131230751;
			
			// aapt resource value: 0x7f080016
			public const int Select = 2131230742;
			
			// aapt resource value: 0x7f08001c
			public const int Space = 2131230748;
			
			// aapt resource value: 0x7f080019
			public const int Space1 = 2131230745;
			
			// aapt resource value: 0x7f080013
			public const int TotalBonusNumbers = 2131230739;
			
			// aapt resource value: 0x7f080012
			public const int TotalNumbers = 2131230738;
			
			// aapt resource value: 0x7f080021
			public const int USAdView = 2131230753;
			
			// aapt resource value: 0x7f080018
			public const int USLotto = 2131230744;
			
			// aapt resource value: 0x7f080015
			public const int UpperBonusLimit = 2131230741;
			
			// aapt resource value: 0x7f080010
			public const int UpperLimit = 2131230736;
			
			// aapt resource value: 0x7f080000
			public const int adjust_height = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int adjust_width = 2131230721;
			
			// aapt resource value: 0x7f08000a
			public const int mainLayout = 2131230730;
			
			// aapt resource value: 0x7f080002
			public const int none = 2131230722;
			
			// aapt resource value: 0x7f080005
			public const int space1 = 2131230725;
			
			// aapt resource value: 0x7f08000d
			public const int space2 = 2131230733;
			
			// aapt resource value: 0x7f080003
			public const int textView1 = 2131230723;
			
			// aapt resource value: 0x7f08000c
			public const int textView2 = 2131230732;
			
			// aapt resource value: 0x7f08000e
			public const int textView3 = 2131230734;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f050000
			public const int google_play_services_version = 2131034112;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CanLotto = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CustomLotto = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int NumbersScreen = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int USLotto = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f04000a
			public const int ApplicationName = 2130968586;
			
			// aapt resource value: 0x7f040009
			public const int Hello = 2130968585;
			
			// aapt resource value: 0x7f04000c
			public const int Numbers_Screen_unit_id = 2130968588;
			
			// aapt resource value: 0x7f040005
			public const int accept = 2130968581;
			
			// aapt resource value: 0x7f04000b
			public const int ad_unit_id = 2130968587;
			
			// aapt resource value: 0x7f040001
			public const int auth_google_play_services_client_facebook_display_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int auth_google_play_services_client_google_display_name = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int common_google_play_services_unknown_issue = 2130968578;
			
			// aapt resource value: 0x7f040008
			public const int create_calendar_message = 2130968584;
			
			// aapt resource value: 0x7f040007
			public const int create_calendar_title = 2130968583;
			
			// aapt resource value: 0x7f040006
			public const int decline = 2130968582;
			
			// aapt resource value: 0x7f040004
			public const int store_picture_message = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int store_picture_title = 2130968579;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060001
			public const int Theme_Custom = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Theme_IAPTheme = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] AdsAttrs = new int[] {
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 0
			public const int AdsAttrs_adSize = 0;
			
			// aapt resource value: 1
			public const int AdsAttrs_adSizes = 1;
			
			// aapt resource value: 2
			public const int AdsAttrs_adUnitId = 2;
			
			public static int[] LoadingImageView = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
